#!/sbin/openrc-run
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

description="Klipper daemon"

command="python2"
command_args="/var/lib/klipper/klippy/klippy.py ${CONFIGFILE:-/etc/klipper/klipper.conf} -l ${LOGFILE:-/var/lib/klipper/klippy.log}"
command_user="${USER:-klipper}:${GROUP:-klipper}"
command_background=true
pidfile="/run/${RC_SVCNAME}.pid"
