#!/bin/sh

src_dir=/opt/dwarf-fortress
default_dst="$HOME/.dwarf-fortress"
dst_dir="${VARIABLE:-$default_dst}"

if [ ! -d "$dst_dir" ]; then
    mkdir -p "$dst_dir"
	cp -a "$src_dir"/* "$dst_dir"/
    if [[ -f "$dst_dir"/dfhack.init-example ]]; then
        cp "$dst_dir"/dfhack.init-example "$dst_dir"/dfhack.init
    fi
fi

cd "$dst_dir" || exit

if [[ -x ./dfhack ]]; then
    exec ./dfhack "$@"
else
    exec ./libs/Dwarf_Fortress "$@"
fi
