#!/sbin/openrc-run
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

description="Octoprint daemon"

command="${OCTOPRINT_EXEC:-/var/lib/octoprint/octo-env/bin/octoprint}"
command_args="serve ${OCTOPRINT_ARGS}"
command_user="${OCTOPRINT_USER:-octoprint}:${OCTOPRINT_GROUP:-octoprint}"
command_background=true
pidfile="/run/${RC_SVCNAME}.pid"
